version: '3.8'

services:
  app:
    build: .
    container_name: sih_sr_app
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/model/RCAN_v2.pth
      - DEVICE=cpu
      - PYTHONUNBUFFERED=1
